# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGSXWwq2fCD0hDi0EjTAYnODZ1bek3YK
"""

import pandas as pd
df_train = pd.read_csv("Titanic_train.csv")
df_test = pd.read_csv("Titanic_test.csv")
df_train.head(50)

df_train.shape

df_train.info()

df_train.describe()

df_train.isnull().sum()

df_train = df_train.drop(['Cabin'], axis = 1)

import matplotlib.pyplot as plt
import seaborn as sns
columns = ['Pclass','Age', 'Fare', 'SibSp', 'Parch']

for col in columns:
  plt.hist(df_train[col], bins = 30)
  plt.title(f"histrogram of {col}")
  plt.show()



sns.boxplot(data = df_train, x = 'Survived', y = 'Age' )

df_train['Age'] = df_train['Age'].fillna(df_train['Age'].median())
df_train['Embarked'] = df_train['Embarked'].fillna(df_train['Embarked'].mode()[0])

df_train = pd.get_dummies(df_train, columns = ['Sex','Embarked'])

x = df_train.drop(['PassengerId','Survived','Name','Ticket'], axis = 1)
y = df_train['Survived']

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(x_train, y_train)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve
y_pred = model.predict(x_test)
y_prob = model.predict_proba(x_test)[:,1]

print("accuracy", accuracy_score(y_test, y_pred))
print("precision", precision_score(y_test, y_pred))
print("recall", recall_score(y_test, y_pred))
print("f1_score",f1_score(y_test, y_pred))
print("roc_score",roc_auc_score(y_test, y_prob))

fpr, tpr , _= roc_curve(y_test, y_prob)
plt.plot(fpr, tpr)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

coefficients = pd.DataFrame({'Feature' : x.columns, 'coefficients' : model.coef_[0]})
coefficients.sort_values(by="coefficients" , ascending = False)

import pickle
pickle.dump(model , open('logistic_model.pkl', 'wb'))
print("Saved logistic_model.pkl")